export default [
    {
      "grade": "12",
      "schoolId": 2,
      "buildingId": 6,
      "courseId": 16016,
      "buildingName": "Syracuse Academy of Science HS",
      "id": 700622151,
      "studentId": 121301741,
      "firstName": "Josepher",
      "lastName": "Felder",
      "section": 2,
      "courseStateCode": "02056CC",
      "star": 155,
      "state": 200,
      "regents": 300,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": 325,
      "pslLevelName": "Level 3",
      "pslColorCode": "#36a2eb",
      "REGENTS-CCAI-score": 78,
      "REGENTS-CCAI-colorCode": "#ffcd56",
      "REGENTS-CCAI-levelName": "L2",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 53,
      "REGENTS-CCG-colorCode": "#ff6384",
      "REGENTS-CCG-levelName": "L1",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "12",
      "schoolId": 2,
      "buildingId": 6,
      "courseId": 16016,
      "buildingName": "Syracuse Academy of Science HS",
      "id": 700622154,
      "studentId": 121301748,
      "firstName": "Abigail",
      "lastName": "Kemmerer",
      "section": 2,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": 326,
      "pslLevelName": "Level 3",
      "pslColorCode": "#36a2eb",
      "REGENTS-CCAI-score": 74,
      "REGENTS-CCAI-colorCode": "#ffcd56",
      "REGENTS-CCAI-levelName": "L2",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 67,
      "REGENTS-CCG-colorCode": "#ffcd56",
      "REGENTS-CCG-levelName": "L2",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "12",
      "schoolId": 2,
      "buildingId": 6,
      "courseId": 16016,
      "buildingName": "Syracuse Academy of Science HS",
      "id": 700622156,
      "studentId": 121301751,
      "firstName": "Devine",
      "lastName": "Mobley",
      "section": 2,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": 287,
      "pslLevelName": "Level 2",
      "pslColorCode": "#ffcd56",
      "REGENTS-CCAI-score": 71,
      "REGENTS-CCAI-colorCode": "#ffcd56",
      "REGENTS-CCAI-levelName": "L2",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 45,
      "REGENTS-CCG-colorCode": "#ff6384",
      "REGENTS-CCG-levelName": "L1",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "11",
      "schoolId": 2,
      "buildingId": 6,
      "courseId": 16016,
      "buildingName": "Syracuse Academy of Science HS",
      "id": 700622387,
      "studentId": 131402052,
      "firstName": "Evan",
      "lastName": "Skinner",
      "section": 1,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": 304,
      "pslLevelName": "Level 2",
      "pslColorCode": "#ffcd56",
      "REGENTS-CCAI-score": 79,
      "REGENTS-CCAI-colorCode": "#ffcd56",
      "REGENTS-CCAI-levelName": "L2",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCAII-score": 51,
      "REGENTS-CCAII-colorCode": "#ff6384",
      "REGENTS-CCAII-levelName": "L1",
      "REGENTS-CCAII-regentsName": "Regents Common Core Algebra II",
      "REGENTS-CCG-score": 63,
      "REGENTS-CCG-colorCode": "#ff6384",
      "REGENTS-CCG-levelName": "L1",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "11",
      "schoolId": 2,
      "buildingId": 6,
      "courseId": 16016,
      "buildingName": "Syracuse Academy of Science HS",
      "id": 700622388,
      "studentId": 131402060,
      "firstName": "Ashley",
      "lastName": "Contreras",
      "section": 1,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": 262,
      "pslLevelName": "Level 1",
      "pslColorCode": "#ff6384",
      "REGENTS-CCAI-score": 67,
      "REGENTS-CCAI-colorCode": "#ffcd56",
      "REGENTS-CCAI-levelName": "L2",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 49,
      "REGENTS-CCG-colorCode": "#ff6384",
      "REGENTS-CCG-levelName": "L1",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "11",
      "schoolId": 2,
      "buildingId": 6,
      "courseId": 16016,
      "buildingName": "Syracuse Academy of Science HS",
      "id": 700622389,
      "studentId": 131402063,
      "firstName": "Jacob",
      "lastName": "Toledo",
      "section": 1,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": 277,
      "pslLevelName": "Level 1",
      "pslColorCode": "#ff6384",
      "REGENTS-CCAI-score": 74,
      "REGENTS-CCAI-colorCode": "#ffcd56",
      "REGENTS-CCAI-levelName": "L2",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 41,
      "REGENTS-CCG-colorCode": "#ff6384",
      "REGENTS-CCG-levelName": "L1",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "12",
      "schoolId": 2,
      "buildingId": 6,
      "courseId": 16016,
      "buildingName": "Syracuse Academy of Science HS",
      "id": 700622395,
      "studentId": 131402083,
      "firstName": "Akeem",
      "lastName": "Stackhouse",
      "section": 3,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": 254,
      "pslLevelName": "Level 1",
      "pslColorCode": "#ff6384",
      "REGENTS-CCAI-score": 56,
      "REGENTS-CCAI-colorCode": "#ff6384",
      "REGENTS-CCAI-levelName": "L1",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 45,
      "REGENTS-CCG-colorCode": "#ff6384",
      "REGENTS-CCG-levelName": "L1",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "12",
      "schoolId": 2,
      "buildingId": 6,
      "courseId": 16016,
      "buildingName": "Syracuse Academy of Science HS",
      "id": 700622398,
      "studentId": 131402090,
      "firstName": "Estevan",
      "lastName": "Morales",
      "section": 2,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": 228,
      "pslLevelName": "Level 1",
      "pslColorCode": "#ff6384",
      "REGENTS-CCAI-score": 65,
      "REGENTS-CCAI-colorCode": "#ffcd56",
      "REGENTS-CCAI-levelName": "L2",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 49,
      "REGENTS-CCG-colorCode": "#ff6384",
      "REGENTS-CCG-levelName": "L1",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "12",
      "schoolId": 2,
      "buildingId": 6,
      "courseId": 16016,
      "buildingName": "Syracuse Academy of Science HS",
      "id": 700622399,
      "studentId": 131402092,
      "firstName": "Wendy",
      "lastName": "O'Reilly-Cordero",
      "section": 3,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": 204,
      "pslLevelName": "Level 1",
      "pslColorCode": "#ff6384",
      "REGENTS-CCAI-score": 66,
      "REGENTS-CCAI-colorCode": "#ffcd56",
      "REGENTS-CCAI-levelName": "L2",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 29,
      "REGENTS-CCG-colorCode": "#ff6384",
      "REGENTS-CCG-levelName": "L1",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "11",
      "schoolId": 13,
      "buildingId": 9,
      "courseId": 16016,
      "buildingName": "Utica Academy of Science HS",
      "id": 700622423,
      "studentId": 141500204,
      "firstName": "Brianna",
      "lastName": "Blum-Jacobs",
      "section": 1,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": null,
      "pslLevelName": null,
      "pslColorCode": "#ffffff",
      "REGENTS-CCAI-score": 81,
      "REGENTS-CCAI-colorCode": "#36a2eb",
      "REGENTS-CCAI-levelName": "L3",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 74,
      "REGENTS-CCG-colorCode": "#ffcd56",
      "REGENTS-CCG-levelName": "L2",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "11",
      "schoolId": 13,
      "buildingId": 9,
      "courseId": 16016,
      "buildingName": "Utica Academy of Science HS",
      "id": 700622424,
      "studentId": 141500205,
      "firstName": "Devanae",
      "lastName": "Bradford",
      "section": 1,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": null,
      "pslLevelName": null,
      "pslColorCode": "#ffffff",
      "REGENTS-CCAI-score": 80,
      "REGENTS-CCAI-colorCode": "#36a2eb",
      "REGENTS-CCAI-levelName": "L3",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 76,
      "REGENTS-CCG-colorCode": "#ffcd56",
      "REGENTS-CCG-levelName": "L2",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "11",
      "schoolId": 13,
      "buildingId": 9,
      "courseId": 16016,
      "buildingName": "Utica Academy of Science HS",
      "id": 700622425,
      "studentId": 141500206,
      "firstName": "Angel",
      "lastName": "Broadus",
      "section": 2,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": null,
      "pslLevelName": null,
      "pslColorCode": "#ffffff"
    },
    {
      "grade": "11",
      "schoolId": 13,
      "buildingId": 9,
      "courseId": 16016,
      "buildingName": "Utica Academy of Science HS",
      "id": 700622429,
      "studentId": 141500215,
      "firstName": "Judah",
      "lastName": "Crowder",
      "section": 2,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": null,
      "pslLevelName": null,
      "pslColorCode": "#ffffff",
      "REGENTS-CCAI-score": 77,
      "REGENTS-CCAI-colorCode": "#ffcd56",
      "REGENTS-CCAI-levelName": "L2",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 64,
      "REGENTS-CCG-colorCode": "#ff6384",
      "REGENTS-CCG-levelName": "L1",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "11",
      "schoolId": 13,
      "buildingId": 9,
      "courseId": 16016,
      "buildingName": "Utica Academy of Science HS",
      "id": 700622432,
      "studentId": 141500222,
      "firstName": "Ilhana",
      "lastName": "Grabovica",
      "section": 2,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": null,
      "pslLevelName": null,
      "pslColorCode": "#ffffff",
      "REGENTS-CCAI-score": 77,
      "REGENTS-CCAI-colorCode": "#ffcd56",
      "REGENTS-CCAI-levelName": "L2",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 74,
      "REGENTS-CCG-colorCode": "#ffcd56",
      "REGENTS-CCG-levelName": "L2",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "11",
      "schoolId": 13,
      "buildingId": 9,
      "courseId": 16016,
      "buildingName": "Utica Academy of Science HS",
      "id": 700622434,
      "studentId": 141500226,
      "firstName": "Vedad",
      "lastName": "Hodzic",
      "section": 1,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": null,
      "pslLevelName": null,
      "pslColorCode": "#ffffff",
      "REGENTS-CCAI-score": 57,
      "REGENTS-CCAI-colorCode": "#ff6384",
      "REGENTS-CCAI-levelName": "L1",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 43,
      "REGENTS-CCG-colorCode": "#ff6384",
      "REGENTS-CCG-levelName": "L1",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "11",
      "schoolId": 13,
      "buildingId": 9,
      "courseId": 16016,
      "buildingName": "Utica Academy of Science HS",
      "id": 700622435,
      "studentId": 141500227,
      "firstName": "Selmir",
      "lastName": "Karup",
      "section": 2,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": null,
      "pslLevelName": null,
      "pslColorCode": "#ffffff",
      "REGENTS-CCAI-score": 68,
      "REGENTS-CCAI-colorCode": "#ffcd56",
      "REGENTS-CCAI-levelName": "L2",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 70,
      "REGENTS-CCG-colorCode": "#ffcd56",
      "REGENTS-CCG-levelName": "L2",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "11",
      "schoolId": 13,
      "buildingId": 9,
      "courseId": 16016,
      "buildingName": "Utica Academy of Science HS",
      "id": 700622436,
      "studentId": 141500228,
      "firstName": "Destiny",
      "lastName": "Kovach",
      "section": 1,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": null,
      "pslLevelName": null,
      "pslColorCode": "#ffffff",
      "REGENTS-CCAI-score": 73,
      "REGENTS-CCAI-colorCode": "#ffcd56",
      "REGENTS-CCAI-levelName": "L2",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 70,
      "REGENTS-CCG-colorCode": "#ffcd56",
      "REGENTS-CCG-levelName": "L2",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "11",
      "schoolId": 13,
      "buildingId": 9,
      "courseId": 16016,
      "buildingName": "Utica Academy of Science HS",
      "id": 700622444,
      "studentId": 141500241,
      "firstName": "Edis",
      "lastName": "Nadarevic",
      "section": 1,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": null,
      "pslLevelName": null,
      "pslColorCode": "#ffffff",
      "REGENTS-CCAI-score": 79,
      "REGENTS-CCAI-colorCode": "#ffcd56",
      "REGENTS-CCAI-levelName": "L2",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 75,
      "REGENTS-CCG-colorCode": "#ffcd56",
      "REGENTS-CCG-levelName": "L2",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "11",
      "schoolId": 13,
      "buildingId": 9,
      "courseId": 16016,
      "buildingName": "Utica Academy of Science HS",
      "id": 700622448,
      "studentId": 141500246,
      "firstName": "Enjoli",
      "lastName": "Rivera",
      "section": 1,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": null,
      "pslLevelName": null,
      "pslColorCode": "#ffffff",
      "REGENTS-CCAI-score": 78,
      "REGENTS-CCAI-colorCode": "#ffcd56",
      "REGENTS-CCAI-levelName": "L2",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I"
    },
    {
      "grade": "11",
      "schoolId": 13,
      "buildingId": 9,
      "courseId": 16016,
      "buildingName": "Utica Academy of Science HS",
      "id": 700622451,
      "studentId": 141500251,
      "firstName": "Darius",
      "lastName": "Stuckman",
      "section": 1,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": null,
      "pslLevelName": null,
      "pslColorCode": "#ffffff",
      "REGENTS-CCAI-score": 72,
      "REGENTS-CCAI-colorCode": "#ffcd56",
      "REGENTS-CCAI-levelName": "L2",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 69,
      "REGENTS-CCG-colorCode": "#ffcd56",
      "REGENTS-CCG-levelName": "L2",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "11",
      "schoolId": 13,
      "buildingId": 9,
      "courseId": 16016,
      "buildingName": "Utica Academy of Science HS",
      "id": 700622453,
      "studentId": 141500254,
      "firstName": "Briana",
      "lastName": "Tinsley",
      "section": 1,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": null,
      "pslLevelName": null,
      "pslColorCode": "#ffffff",
      "REGENTS-CCAI-score": 73,
      "REGENTS-CCAI-colorCode": "#ffcd56",
      "REGENTS-CCAI-levelName": "L2",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 69,
      "REGENTS-CCG-colorCode": "#ffcd56",
      "REGENTS-CCG-levelName": "L2",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "11",
      "schoolId": 13,
      "buildingId": 9,
      "courseId": 16016,
      "buildingName": "Utica Academy of Science HS",
      "id": 700622456,
      "studentId": 141500259,
      "firstName": "Robbie Lee",
      "lastName": "Washington",
      "section": 1,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": null,
      "pslLevelName": null,
      "pslColorCode": "#ffffff",
      "REGENTS-CCAI-score": 78,
      "REGENTS-CCAI-colorCode": "#ffcd56",
      "REGENTS-CCAI-levelName": "L2",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 74,
      "REGENTS-CCG-colorCode": "#ffcd56",
      "REGENTS-CCG-levelName": "L2",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "11",
      "schoolId": 2,
      "buildingId": 6,
      "courseId": 16016,
      "buildingName": "Syracuse Academy of Science HS",
      "id": 700622582,
      "studentId": 141502301,
      "firstName": "Dominique",
      "lastName": "Owens",
      "section": 1,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": 292,
      "pslLevelName": "Level 2",
      "pslColorCode": "#ffcd56",
      "REGENTS-CCAI-score": 70,
      "REGENTS-CCAI-colorCode": "#ffcd56",
      "REGENTS-CCAI-levelName": "L2",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 56,
      "REGENTS-CCG-colorCode": "#ff6384",
      "REGENTS-CCG-levelName": "L1",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "11",
      "schoolId": 2,
      "buildingId": 6,
      "courseId": 16016,
      "buildingName": "Syracuse Academy of Science HS",
      "id": 700622591,
      "studentId": 141502317,
      "firstName": "Alonzo",
      "lastName": "Fitch",
      "section": 1,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": 298,
      "pslLevelName": "Level 2",
      "pslColorCode": "#ffcd56",
      "REGENTS-CCAI-score": 62,
      "REGENTS-CCAI-colorCode": "#ff6384",
      "REGENTS-CCAI-levelName": "L1",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 49,
      "REGENTS-CCG-colorCode": "#ff6384",
      "REGENTS-CCG-levelName": "L1",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "11",
      "schoolId": 2,
      "buildingId": 6,
      "courseId": 16016,
      "buildingName": "Syracuse Academy of Science HS",
      "id": 700622595,
      "studentId": 141502325,
      "firstName": "Aniyah",
      "lastName": "Everson",
      "section": 1,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": 289,
      "pslLevelName": "Level 2",
      "pslColorCode": "#ffcd56",
      "REGENTS-CCAI-score": 57,
      "REGENTS-CCAI-colorCode": "#ff6384",
      "REGENTS-CCAI-levelName": "L1",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 49,
      "REGENTS-CCG-colorCode": "#ff6384",
      "REGENTS-CCG-levelName": "L1",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "12",
      "schoolId": 2,
      "buildingId": 6,
      "courseId": 16016,
      "buildingName": "Syracuse Academy of Science HS",
      "id": 700622597,
      "studentId": 141502328,
      "firstName": "Mosiah",
      "lastName": "Johnson",
      "section": 3,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": 303,
      "pslLevelName": "Level 2",
      "pslColorCode": "#ffcd56",
      "REGENTS-CCAI-score": 70,
      "REGENTS-CCAI-colorCode": "#ffcd56",
      "REGENTS-CCAI-levelName": "L2",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 71,
      "REGENTS-CCG-colorCode": "#ffcd56",
      "REGENTS-CCG-levelName": "L2",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "12",
      "schoolId": 2,
      "buildingId": 6,
      "courseId": 16016,
      "buildingName": "Syracuse Academy of Science HS",
      "id": 700622598,
      "studentId": 141502329,
      "firstName": "Maxine",
      "lastName": "Parker",
      "section": 1,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": 266,
      "pslLevelName": "Level 1",
      "pslColorCode": "#ff6384",
      "REGENTS-CCAI-score": 57,
      "REGENTS-CCAI-colorCode": "#ff6384",
      "REGENTS-CCAI-levelName": "L1",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I"
    },
    {
      "grade": "12",
      "schoolId": 2,
      "buildingId": 6,
      "courseId": 16016,
      "buildingName": "Syracuse Academy of Science HS",
      "id": 700622599,
      "studentId": 141502330,
      "firstName": "Farhiyo",
      "lastName": "Abdullahi",
      "section": 3,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": 284,
      "pslLevelName": "Level 1",
      "pslColorCode": "#ff6384",
      "REGENTS-CCAI-score": 71,
      "REGENTS-CCAI-colorCode": "#ffcd56",
      "REGENTS-CCAI-levelName": "L2",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 50,
      "REGENTS-CCG-colorCode": "#ff6384",
      "REGENTS-CCG-levelName": "L1",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "12",
      "schoolId": 2,
      "buildingId": 6,
      "courseId": 16016,
      "buildingName": "Syracuse Academy of Science HS",
      "id": 700622604,
      "studentId": 141502341,
      "firstName": "Star",
      "lastName": "Galvan",
      "section": 2,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": 292,
      "pslLevelName": "Level 2",
      "pslColorCode": "#ffcd56",
      "REGENTS-CCAI-score": 65,
      "REGENTS-CCAI-colorCode": "#ffcd56",
      "REGENTS-CCAI-levelName": "L2",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 45,
      "REGENTS-CCG-colorCode": "#ff6384",
      "REGENTS-CCG-levelName": "L1",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "12",
      "schoolId": 2,
      "buildingId": 6,
      "courseId": 16016,
      "buildingName": "Syracuse Academy of Science HS",
      "id": 700622605,
      "studentId": 141502342,
      "firstName": "Abdo",
      "lastName": "Alomeri",
      "section": 3,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": 246,
      "pslLevelName": "Level 1",
      "pslColorCode": "#ff6384",
      "REGENTS-CCAI-score": 71,
      "REGENTS-CCAI-colorCode": "#ffcd56",
      "REGENTS-CCAI-levelName": "L2",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 41,
      "REGENTS-CCG-colorCode": "#ff6384",
      "REGENTS-CCG-levelName": "L1",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "12",
      "schoolId": 2,
      "buildingId": 6,
      "courseId": 16016,
      "buildingName": "Syracuse Academy of Science HS",
      "id": 700622631,
      "studentId": 141502400,
      "firstName": "Angelina",
      "lastName": "Galvan",
      "section": 3,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": 246,
      "pslLevelName": "Level 1",
      "pslColorCode": "#ff6384"
    },
    {
      "grade": "12",
      "schoolId": 2,
      "buildingId": 6,
      "courseId": 16016,
      "buildingName": "Syracuse Academy of Science HS",
      "id": 700622638,
      "studentId": 141502411,
      "firstName": "Te'Quan",
      "lastName": "Wright",
      "section": 2,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": 246,
      "pslLevelName": "Level 1",
      "pslColorCode": "#ff6384",
      "REGENTS-CCAI-score": 63,
      "REGENTS-CCAI-colorCode": "#ff6384",
      "REGENTS-CCAI-levelName": "L1",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 50,
      "REGENTS-CCG-colorCode": "#ff6384",
      "REGENTS-CCG-levelName": "L1",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "12",
      "schoolId": 2,
      "buildingId": 6,
      "courseId": 16016,
      "buildingName": "Syracuse Academy of Science HS",
      "id": 700622680,
      "studentId": 141502468,
      "firstName": "Jesus",
      "lastName": "Gorra Andres",
      "section": 3,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": 270,
      "pslLevelName": "Level 1",
      "pslColorCode": "#ff6384",
      "REGENTS-CCAI-score": 77,
      "REGENTS-CCAI-colorCode": "#ffcd56",
      "REGENTS-CCAI-levelName": "L2",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 55,
      "REGENTS-CCG-colorCode": "#ff6384",
      "REGENTS-CCG-levelName": "L1",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "10",
      "schoolId": 13,
      "buildingId": 9,
      "courseId": 16016,
      "buildingName": "Utica Academy of Science HS",
      "id": 700622699,
      "studentId": 151600011,
      "firstName": "Dzana",
      "lastName": "Borovic",
      "section": 1,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": null,
      "pslLevelName": null,
      "pslColorCode": "#ffffff",
      "REGENTS-CCAI-score": 92,
      "REGENTS-CCAI-colorCode": "#4bc0c0",
      "REGENTS-CCAI-levelName": "L4",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 87,
      "REGENTS-CCG-colorCode": "#4bc0c0",
      "REGENTS-CCG-levelName": "L4",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "10",
      "schoolId": 13,
      "buildingId": 9,
      "courseId": 16016,
      "buildingName": "Utica Academy of Science HS",
      "id": 700622701,
      "studentId": 151600013,
      "firstName": "Erna",
      "lastName": "Bulaja",
      "section": 2,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": null,
      "pslLevelName": null,
      "pslColorCode": "#ffffff",
      "REGENTS-CCAI-score": 86,
      "REGENTS-CCAI-colorCode": "#4bc0c0",
      "REGENTS-CCAI-levelName": "L4",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 83,
      "REGENTS-CCG-colorCode": "#36a2eb",
      "REGENTS-CCG-levelName": "L3",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "10",
      "schoolId": 13,
      "buildingId": 9,
      "courseId": 16016,
      "buildingName": "Utica Academy of Science HS",
      "id": 700622714,
      "studentId": 151600029,
      "firstName": "Lauren",
      "lastName": "Jackson",
      "section": 2,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": null,
      "pslLevelName": null,
      "pslColorCode": "#ffffff",
      "REGENTS-CCAI-score": 80,
      "REGENTS-CCAI-colorCode": "#36a2eb",
      "REGENTS-CCAI-levelName": "L3",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 80,
      "REGENTS-CCG-colorCode": "#36a2eb",
      "REGENTS-CCG-levelName": "L3",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "10",
      "schoolId": 13,
      "buildingId": 9,
      "courseId": 16016,
      "buildingName": "Utica Academy of Science HS",
      "id": 700622724,
      "studentId": 151600043,
      "firstName": "Olivia",
      "lastName": "O'Sullivan Green",
      "section": 1,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": null,
      "pslLevelName": null,
      "pslColorCode": "#ffffff",
      "REGENTS-CCAI-score": 75,
      "REGENTS-CCAI-colorCode": "#ffcd56",
      "REGENTS-CCAI-levelName": "L2",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 72,
      "REGENTS-CCG-colorCode": "#ffcd56",
      "REGENTS-CCG-levelName": "L2",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "10",
      "schoolId": 13,
      "buildingId": 9,
      "courseId": 16016,
      "buildingName": "Utica Academy of Science HS",
      "id": 700622732,
      "studentId": 151600053,
      "firstName": "Clifton",
      "lastName": "Rogers III",
      "section": 1,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": null,
      "pslLevelName": null,
      "pslColorCode": "#ffffff",
      "REGENTS-CCAI-score": 87,
      "REGENTS-CCAI-colorCode": "#4bc0c0",
      "REGENTS-CCAI-levelName": "L4",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 88,
      "REGENTS-CCG-colorCode": "#4bc0c0",
      "REGENTS-CCG-levelName": "L4",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "10",
      "schoolId": 13,
      "buildingId": 9,
      "courseId": 16016,
      "buildingName": "Utica Academy of Science HS",
      "id": 700622734,
      "studentId": 151600056,
      "firstName": "Hannah",
      "lastName": "Schichler",
      "section": 2,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": null,
      "pslLevelName": null,
      "pslColorCode": "#ffffff",
      "REGENTS-CCAI-score": 83,
      "REGENTS-CCAI-colorCode": "#36a2eb",
      "REGENTS-CCAI-levelName": "L3",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 75,
      "REGENTS-CCG-colorCode": "#ffcd56",
      "REGENTS-CCG-levelName": "L2",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "10",
      "schoolId": 13,
      "buildingId": 9,
      "courseId": 16016,
      "buildingName": "Utica Academy of Science HS",
      "id": 700622745,
      "studentId": 151600068,
      "firstName": "Amina",
      "lastName": "Zagorica",
      "section": 1,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": null,
      "pslLevelName": null,
      "pslColorCode": "#ffffff",
      "REGENTS-CCAI-score": 83,
      "REGENTS-CCAI-colorCode": "#36a2eb",
      "REGENTS-CCAI-levelName": "L3",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 76,
      "REGENTS-CCG-colorCode": "#ffcd56",
      "REGENTS-CCG-levelName": "L2",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "11",
      "schoolId": 13,
      "buildingId": 9,
      "courseId": 16016,
      "buildingName": "Utica Academy of Science HS",
      "id": 700622748,
      "studentId": 151600071,
      "firstName": "Almina",
      "lastName": "Beganovic",
      "section": 1,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": null,
      "pslLevelName": null,
      "pslColorCode": "#ffffff",
      "REGENTS-CCAI-score": 76,
      "REGENTS-CCAI-colorCode": "#ffcd56",
      "REGENTS-CCAI-levelName": "L2",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 70,
      "REGENTS-CCG-colorCode": "#ffcd56",
      "REGENTS-CCG-levelName": "L2",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "11",
      "schoolId": 13,
      "buildingId": 9,
      "courseId": 16016,
      "buildingName": "Utica Academy of Science HS",
      "id": 700622791,
      "studentId": 151600157,
      "firstName": "Zayauna",
      "lastName": "Rodriguez",
      "section": 1,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": null,
      "pslLevelName": null,
      "pslColorCode": "#ffffff",
      "REGENTS-CCAI-score": 71,
      "REGENTS-CCAI-colorCode": "#ffcd56",
      "REGENTS-CCAI-levelName": "L2",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 67,
      "REGENTS-CCG-colorCode": "#ffcd56",
      "REGENTS-CCG-levelName": "L2",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "11",
      "schoolId": 2,
      "buildingId": 6,
      "courseId": 16016,
      "buildingName": "Syracuse Academy of Science HS",
      "id": 700622909,
      "studentId": 151602599,
      "firstName": "Joseph",
      "lastName": "Divincenzo",
      "section": 1,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": 244,
      "pslLevelName": "Level 1",
      "pslColorCode": "#ff6384",
      "REGENTS-CCAI-score": 62,
      "REGENTS-CCAI-colorCode": "#ff6384",
      "REGENTS-CCAI-levelName": "L1",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 58,
      "REGENTS-CCG-colorCode": "#ff6384",
      "REGENTS-CCG-levelName": "L1",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "11",
      "schoolId": 2,
      "buildingId": 6,
      "courseId": 16016,
      "buildingName": "Syracuse Academy of Science HS",
      "id": 700622932,
      "studentId": 151602633,
      "firstName": "Mahogany",
      "lastName": "Saffold",
      "section": 1,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": 277,
      "pslLevelName": "Level 1",
      "pslColorCode": "#ff6384",
      "REGENTS-CCAI-score": 66,
      "REGENTS-CCAI-colorCode": "#ffcd56",
      "REGENTS-CCAI-levelName": "L2",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 52,
      "REGENTS-CCG-colorCode": "#ff6384",
      "REGENTS-CCG-levelName": "L1",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "10",
      "schoolId": 13,
      "buildingId": 9,
      "courseId": 16016,
      "buildingName": "Utica Academy of Science HS",
      "id": 700623027,
      "studentId": 161700061,
      "firstName": "Julian",
      "lastName": "Bradley",
      "section": 2,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": null,
      "pslLevelName": null,
      "pslColorCode": "#ffffff",
      "REGENTS-CCAI-score": 84,
      "REGENTS-CCAI-colorCode": "#36a2eb",
      "REGENTS-CCAI-levelName": "L3",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 83,
      "REGENTS-CCG-colorCode": "#36a2eb",
      "REGENTS-CCG-levelName": "L3",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "10",
      "schoolId": 13,
      "buildingId": 9,
      "courseId": 16016,
      "buildingName": "Utica Academy of Science HS",
      "id": 700623030,
      "studentId": 161700066,
      "firstName": "Ittikorn",
      "lastName": "Keawpinna",
      "section": 2,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": null,
      "pslLevelName": null,
      "pslColorCode": "#ffffff",
      "REGENTS-CCAI-score": 80,
      "REGENTS-CCAI-colorCode": "#36a2eb",
      "REGENTS-CCAI-levelName": "L3",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 79,
      "REGENTS-CCG-colorCode": "#ffcd56",
      "REGENTS-CCG-levelName": "L2",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "10",
      "schoolId": 13,
      "buildingId": 9,
      "courseId": 16016,
      "buildingName": "Utica Academy of Science HS",
      "id": 700623033,
      "studentId": 161700069,
      "firstName": "Savannah",
      "lastName": "Noel",
      "section": 1,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": null,
      "pslLevelName": null,
      "pslColorCode": "#ffffff",
      "REGENTS-CCAI-score": 89,
      "REGENTS-CCAI-colorCode": "#4bc0c0",
      "REGENTS-CCAI-levelName": "L4",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 84,
      "REGENTS-CCG-colorCode": "#36a2eb",
      "REGENTS-CCG-levelName": "L3",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "10",
      "schoolId": 13,
      "buildingId": 9,
      "courseId": 16016,
      "buildingName": "Utica Academy of Science HS",
      "id": 700623034,
      "studentId": 161700070,
      "firstName": "Siulee",
      "lastName": "Olivera",
      "section": 1,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": null,
      "pslLevelName": null,
      "pslColorCode": "#ffffff",
      "REGENTS-CCAI-score": 88,
      "REGENTS-CCAI-colorCode": "#4bc0c0",
      "REGENTS-CCAI-levelName": "L4",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 84,
      "REGENTS-CCG-colorCode": "#36a2eb",
      "REGENTS-CCG-levelName": "L3",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "11",
      "schoolId": 13,
      "buildingId": 9,
      "courseId": 16016,
      "buildingName": "Utica Academy of Science HS",
      "id": 700623042,
      "studentId": 161700080,
      "firstName": "Justin",
      "lastName": "Brown",
      "section": 2,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": null,
      "pslLevelName": null,
      "pslColorCode": "#ffffff",
      "REGENTS-CCAI-score": 77,
      "REGENTS-CCAI-colorCode": "#ffcd56",
      "REGENTS-CCAI-levelName": "L2",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 70,
      "REGENTS-CCG-colorCode": "#ffcd56",
      "REGENTS-CCG-levelName": "L2",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "11",
      "schoolId": 13,
      "buildingId": 9,
      "courseId": 16016,
      "buildingName": "Utica Academy of Science HS",
      "id": 700623047,
      "studentId": 161700087,
      "firstName": "Tiah",
      "lastName": "Wormuth",
      "section": 2,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": null,
      "pslLevelName": null,
      "pslColorCode": "#ffffff",
      "REGENTS-CCAI-score": 74,
      "REGENTS-CCAI-colorCode": "#ffcd56",
      "REGENTS-CCAI-levelName": "L2",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 67,
      "REGENTS-CCG-colorCode": "#ffcd56",
      "REGENTS-CCG-levelName": "L2",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "10",
      "schoolId": 13,
      "buildingId": 9,
      "courseId": 16016,
      "buildingName": "Utica Academy of Science HS",
      "id": 700623063,
      "studentId": 161700111,
      "firstName": "Rawa",
      "lastName": "Almasqari",
      "section": 1,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": null,
      "pslLevelName": null,
      "pslColorCode": "#ffffff",
      "REGENTS-CCAI-score": 89,
      "REGENTS-CCAI-colorCode": "#4bc0c0",
      "REGENTS-CCAI-levelName": "L4",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 81,
      "REGENTS-CCG-colorCode": "#36a2eb",
      "REGENTS-CCG-levelName": "L3",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "11",
      "schoolId": 13,
      "buildingId": 9,
      "courseId": 16016,
      "buildingName": "Utica Academy of Science HS",
      "id": 700623067,
      "studentId": 161700117,
      "firstName": "Ko Sei",
      "lastName": "Ma",
      "section": 1,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": null,
      "pslLevelName": null,
      "pslColorCode": "#ffffff",
      "REGENTS-CCAI-score": 77,
      "REGENTS-CCAI-colorCode": "#ffcd56",
      "REGENTS-CCAI-levelName": "L2",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 83,
      "REGENTS-CCG-colorCode": "#36a2eb",
      "REGENTS-CCG-levelName": "L3",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "11",
      "schoolId": 13,
      "buildingId": 9,
      "courseId": 16016,
      "buildingName": "Utica Academy of Science HS",
      "id": 700623074,
      "studentId": 161700124,
      "firstName": "Ermin",
      "lastName": "Novalic",
      "section": 1,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": null,
      "pslLevelName": null,
      "pslColorCode": "#ffffff",
      "REGENTS-CCAI-score": 73,
      "REGENTS-CCAI-colorCode": "#ffcd56",
      "REGENTS-CCAI-levelName": "L2",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 72,
      "REGENTS-CCG-colorCode": "#ffcd56",
      "REGENTS-CCG-levelName": "L2",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "10",
      "schoolId": 13,
      "buildingId": 9,
      "courseId": 16016,
      "buildingName": "Utica Academy of Science HS",
      "id": 700623085,
      "studentId": 161700139,
      "firstName": "Elias",
      "lastName": "Romero",
      "section": 2,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": null,
      "pslLevelName": null,
      "pslColorCode": "#ffffff",
      "REGENTS-CCAI-score": 84,
      "REGENTS-CCAI-colorCode": "#36a2eb",
      "REGENTS-CCAI-levelName": "L3",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 79,
      "REGENTS-CCG-colorCode": "#ffcd56",
      "REGENTS-CCG-levelName": "L2",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "11",
      "schoolId": 13,
      "buildingId": 9,
      "courseId": 16016,
      "buildingName": "Utica Academy of Science HS",
      "id": 700623092,
      "studentId": 161700147,
      "firstName": "Jandier",
      "lastName": "Almonte",
      "section": 1,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": null,
      "pslLevelName": null,
      "pslColorCode": "#ffffff",
      "REGENTS-CCAI-score": 78,
      "REGENTS-CCAI-colorCode": "#ffcd56",
      "REGENTS-CCAI-levelName": "L2",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 72,
      "REGENTS-CCG-colorCode": "#ffcd56",
      "REGENTS-CCG-levelName": "L2",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "12",
      "schoolId": 2,
      "buildingId": 6,
      "courseId": 16016,
      "buildingName": "Syracuse Academy of Science HS",
      "id": 700623164,
      "studentId": 161702742,
      "firstName": "Jordyn",
      "lastName": "Cox",
      "section": 3,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": null,
      "pslLevelName": null,
      "pslColorCode": "#ffffff",
      "REGENTS-CCAI-score": 77,
      "REGENTS-CCAI-colorCode": "#ffcd56",
      "REGENTS-CCAI-levelName": "L2",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCAII-score": 67,
      "REGENTS-CCAII-colorCode": "#ffcd56",
      "REGENTS-CCAII-levelName": "L2",
      "REGENTS-CCAII-regentsName": "Regents Common Core Algebra II",
      "REGENTS-CCG-score": 67,
      "REGENTS-CCG-colorCode": "#ffcd56",
      "REGENTS-CCG-levelName": "L2",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "11",
      "schoolId": 2,
      "buildingId": 6,
      "courseId": 16016,
      "buildingName": "Syracuse Academy of Science HS",
      "id": 700623229,
      "studentId": 161702814,
      "firstName": "Akasha",
      "lastName": "Bey",
      "section": 1,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": 244,
      "pslLevelName": "Level 1",
      "pslColorCode": "#ff6384",
      "REGENTS-CCAI-score": 68,
      "REGENTS-CCAI-colorCode": "#ffcd56",
      "REGENTS-CCAI-levelName": "L2",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 51,
      "REGENTS-CCG-colorCode": "#ff6384",
      "REGENTS-CCG-levelName": "L1",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "12",
      "schoolId": 2,
      "buildingId": 6,
      "courseId": 16016,
      "buildingName": "Syracuse Academy of Science HS",
      "id": 700623240,
      "studentId": 161702825,
      "firstName": "Odell",
      "lastName": "Darby Jr.",
      "section": 2,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": null,
      "pslLevelName": null,
      "pslColorCode": "#ffffff",
      "REGENTS-CCAI-score": 58,
      "REGENTS-CCAI-colorCode": "#ff6384",
      "REGENTS-CCAI-levelName": "L1",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 29,
      "REGENTS-CCG-colorCode": "#ff6384",
      "REGENTS-CCG-levelName": "L1",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "12",
      "schoolId": 2,
      "buildingId": 6,
      "courseId": 16016,
      "buildingName": "Syracuse Academy of Science HS",
      "id": 700623242,
      "studentId": 161702828,
      "firstName": "Royalty",
      "lastName": "Heath",
      "section": 2,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": null,
      "pslLevelName": null,
      "pslColorCode": "#ffffff"
    },
    {
      "grade": "12",
      "schoolId": 2,
      "buildingId": 6,
      "courseId": 16016,
      "buildingName": "Syracuse Academy of Science HS",
      "id": 700623244,
      "studentId": 161702830,
      "firstName": "Issac",
      "lastName": "Gyder",
      "section": 3,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": null,
      "pslLevelName": null,
      "pslColorCode": "#ffffff",
      "REGENTS-CCG-score": 55,
      "REGENTS-CCG-colorCode": "#ff6384",
      "REGENTS-CCG-levelName": "L1",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "12",
      "schoolId": 2,
      "buildingId": 6,
      "courseId": 16016,
      "buildingName": "Syracuse Academy of Science HS",
      "id": 700623245,
      "studentId": 161702831,
      "firstName": "Jair",
      "lastName": "Hunt",
      "section": 2,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": null,
      "pslLevelName": null,
      "pslColorCode": "#ffffff",
      "REGENTS-CCAI-score": 67,
      "REGENTS-CCAI-colorCode": "#ffcd56",
      "REGENTS-CCAI-levelName": "L2",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 58,
      "REGENTS-CCG-colorCode": "#ff6384",
      "REGENTS-CCG-levelName": "L1",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "12",
      "schoolId": 2,
      "buildingId": 6,
      "courseId": 16016,
      "buildingName": "Syracuse Academy of Science HS",
      "id": 700623246,
      "studentId": 161702832,
      "firstName": "Taalib",
      "lastName": "Johnson",
      "section": 3,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": null,
      "pslLevelName": null,
      "pslColorCode": "#ffffff",
      "REGENTS-CCAI-score": 76,
      "REGENTS-CCAI-colorCode": "#ffcd56",
      "REGENTS-CCAI-levelName": "L2",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 60,
      "REGENTS-CCG-colorCode": "#ff6384",
      "REGENTS-CCG-levelName": "L1",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "12",
      "schoolId": 2,
      "buildingId": 6,
      "courseId": 16016,
      "buildingName": "Syracuse Academy of Science HS",
      "id": 700623248,
      "studentId": 161702834,
      "firstName": "Augustine",
      "lastName": "Jusu",
      "section": 2,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": null,
      "pslLevelName": null,
      "pslColorCode": "#ffffff",
      "REGENTS-CCAI-score": 66,
      "REGENTS-CCAI-colorCode": "#ffcd56",
      "REGENTS-CCAI-levelName": "L2",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 55,
      "REGENTS-CCG-colorCode": "#ff6384",
      "REGENTS-CCG-levelName": "L1",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "12",
      "schoolId": 2,
      "buildingId": 6,
      "courseId": 16016,
      "buildingName": "Syracuse Academy of Science HS",
      "id": 700623249,
      "studentId": 161702835,
      "firstName": "Longar",
      "lastName": "Longar",
      "section": 3,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": null,
      "pslLevelName": null,
      "pslColorCode": "#ffffff",
      "REGENTS-CCAI-score": 56,
      "REGENTS-CCAI-colorCode": "#ff6384",
      "REGENTS-CCAI-levelName": "L1",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCAII-score": 51,
      "REGENTS-CCAII-colorCode": "#ff6384",
      "REGENTS-CCAII-levelName": "L1",
      "REGENTS-CCAII-regentsName": "Regents Common Core Algebra II"
    },
    {
      "grade": "12",
      "schoolId": 2,
      "buildingId": 6,
      "courseId": 16016,
      "buildingName": "Syracuse Academy of Science HS",
      "id": 700623250,
      "studentId": 161702836,
      "firstName": "Antwon",
      "lastName": "Mcmullen",
      "section": 3,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": null,
      "pslLevelName": null,
      "pslColorCode": "#ffffff",
      "REGENTS-CCAI-score": 67,
      "REGENTS-CCAI-colorCode": "#ffcd56",
      "REGENTS-CCAI-levelName": "L2",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 48,
      "REGENTS-CCG-colorCode": "#ff6384",
      "REGENTS-CCG-levelName": "L1",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "11",
      "schoolId": 2,
      "buildingId": 6,
      "courseId": 16016,
      "buildingName": "Syracuse Academy of Science HS",
      "id": 700623255,
      "studentId": 161702841,
      "firstName": "Sean",
      "lastName": "Parody",
      "section": 1,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": null,
      "pslLevelName": null,
      "pslColorCode": "#ffffff",
      "REGENTS-CCAI-score": 63,
      "REGENTS-CCAI-colorCode": "#ff6384",
      "REGENTS-CCAI-levelName": "L1",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 52,
      "REGENTS-CCG-colorCode": "#ff6384",
      "REGENTS-CCG-levelName": "L1",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "12",
      "schoolId": 2,
      "buildingId": 6,
      "courseId": 16016,
      "buildingName": "Syracuse Academy of Science HS",
      "id": 700623259,
      "studentId": 161702845,
      "firstName": "Ta'Rae",
      "lastName": "Tyler",
      "section": 2,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": null,
      "pslLevelName": null,
      "pslColorCode": "#ffffff",
      "REGENTS-CCAI-score": 65,
      "REGENTS-CCAI-colorCode": "#ffcd56",
      "REGENTS-CCAI-levelName": "L2",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 49,
      "REGENTS-CCG-colorCode": "#ff6384",
      "REGENTS-CCG-levelName": "L1",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "12",
      "schoolId": 2,
      "buildingId": 6,
      "courseId": 16016,
      "buildingName": "Syracuse Academy of Science HS",
      "id": 700623260,
      "studentId": 161702846,
      "firstName": "Sawlah",
      "lastName": "Yahya",
      "section": 2,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": null,
      "pslLevelName": null,
      "pslColorCode": "#ffffff",
      "REGENTS-CCAI-score": 55,
      "REGENTS-CCAI-colorCode": "#ff6384",
      "REGENTS-CCAI-levelName": "L1",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 26,
      "REGENTS-CCG-colorCode": "#ff6384",
      "REGENTS-CCG-levelName": "L1",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "12",
      "schoolId": 2,
      "buildingId": 6,
      "courseId": 16016,
      "buildingName": "Syracuse Academy of Science HS",
      "id": 700623277,
      "studentId": 161702866,
      "firstName": "Maranyelin",
      "lastName": "Edwards",
      "section": 2,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": null,
      "pslLevelName": null,
      "pslColorCode": "#ffffff",
      "REGENTS-CCAI-score": 59,
      "REGENTS-CCAI-colorCode": "#ff6384",
      "REGENTS-CCAI-levelName": "L1",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 32,
      "REGENTS-CCG-colorCode": "#ff6384",
      "REGENTS-CCG-levelName": "L1",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "12",
      "schoolId": 2,
      "buildingId": 6,
      "courseId": 16016,
      "buildingName": "Syracuse Academy of Science HS",
      "id": 700623293,
      "studentId": 161702882,
      "firstName": "Mallory",
      "lastName": "Drake",
      "section": 1,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": null,
      "pslLevelName": null,
      "pslColorCode": "#ffffff",
      "REGENTS-CCAI-score": 76,
      "REGENTS-CCAI-colorCode": "#ffcd56",
      "REGENTS-CCAI-levelName": "L2",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 65,
      "REGENTS-CCG-colorCode": "#ffcd56",
      "REGENTS-CCG-levelName": "L2",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "12",
      "schoolId": 2,
      "buildingId": 6,
      "courseId": 16016,
      "buildingName": "Syracuse Academy of Science HS",
      "id": 700623307,
      "studentId": 16172883,
      "firstName": "Justine",
      "lastName": "Bell",
      "section": 3,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": null,
      "pslLevelName": null,
      "pslColorCode": "#ffffff",
      "REGENTS-CCAI-score": 66,
      "REGENTS-CCAI-colorCode": "#ffcd56",
      "REGENTS-CCAI-levelName": "L2",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 45,
      "REGENTS-CCG-colorCode": "#ff6384",
      "REGENTS-CCG-levelName": "L1",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "11",
      "schoolId": 13,
      "buildingId": 9,
      "courseId": 16016,
      "buildingName": "Utica Academy of Science HS",
      "id": 700623461,
      "studentId": 171801158,
      "firstName": "Janessa",
      "lastName": "James",
      "section": 1,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": null,
      "pslLevelName": null,
      "pslColorCode": "#ffffff",
      "REGENTS-CCAI-score": 75,
      "REGENTS-CCAI-colorCode": "#ffcd56",
      "REGENTS-CCAI-levelName": "L2",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 78,
      "REGENTS-CCG-colorCode": "#ffcd56",
      "REGENTS-CCG-levelName": "L2",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "11",
      "schoolId": 13,
      "buildingId": 9,
      "courseId": 16016,
      "buildingName": "Utica Academy of Science HS",
      "id": 700623479,
      "studentId": 171801179,
      "firstName": "Lejla",
      "lastName": "Becirevic",
      "section": 2,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": null,
      "pslLevelName": null,
      "pslColorCode": "#ffffff",
      "REGENTS-CCAI-score": 66,
      "REGENTS-CCAI-colorCode": "#ffcd56",
      "REGENTS-CCAI-levelName": "L2",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 52,
      "REGENTS-CCG-colorCode": "#ff6384",
      "REGENTS-CCG-levelName": "L1",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "12",
      "schoolId": 2,
      "buildingId": 6,
      "courseId": 16016,
      "buildingName": "Syracuse Academy of Science HS",
      "id": 700623826,
      "studentId": 171801563,
      "firstName": "Elizabeth",
      "lastName": "Kaitesi",
      "section": 2,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": null,
      "pslLevelName": null,
      "pslColorCode": "#ffffff",
      "REGENTS-CCAI-score": 66,
      "REGENTS-CCAI-colorCode": "#ffcd56",
      "REGENTS-CCAI-levelName": "L2",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I"
    },
    {
      "grade": "11",
      "schoolId": 2,
      "buildingId": 6,
      "courseId": 16016,
      "buildingName": "Syracuse Academy of Science HS",
      "id": 700623847,
      "studentId": 171801589,
      "firstName": "Yahshona",
      "lastName": "Jackson",
      "section": 1,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": null,
      "pslLevelName": null,
      "pslColorCode": "#ffffff",
      "REGENTS-CCAI-score": 78,
      "REGENTS-CCAI-colorCode": "#ffcd56",
      "REGENTS-CCAI-levelName": "L2",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 65,
      "REGENTS-CCG-colorCode": "#ffcd56",
      "REGENTS-CCG-levelName": "L2",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "11",
      "schoolId": 2,
      "buildingId": 6,
      "courseId": 16016,
      "buildingName": "Syracuse Academy of Science HS",
      "id": 700623953,
      "studentId": 181901113,
      "firstName": "Maher",
      "lastName": "Mobaraz",
      "section": 1,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": null,
      "pslLevelName": null,
      "pslColorCode": "#ffffff",
      "REGENTS-CCAI-score": 76,
      "REGENTS-CCAI-colorCode": "#ffcd56",
      "REGENTS-CCAI-levelName": "L2",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 60,
      "REGENTS-CCG-colorCode": "#ff6384",
      "REGENTS-CCG-levelName": "L1",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "11",
      "schoolId": 2,
      "buildingId": 6,
      "courseId": 16016,
      "buildingName": "Syracuse Academy of Science HS",
      "id": 700624086,
      "studentId": 181901266,
      "firstName": "Kasheem",
      "lastName": "Boatman",
      "section": 1,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": null,
      "pslLevelName": null,
      "pslColorCode": "#ffffff",
      "REGENTS-CCAI-score": 67,
      "REGENTS-CCAI-colorCode": "#ffcd56",
      "REGENTS-CCAI-levelName": "L2",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 53,
      "REGENTS-CCG-colorCode": "#ff6384",
      "REGENTS-CCG-levelName": "L1",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "11",
      "schoolId": 2,
      "buildingId": 6,
      "courseId": 16016,
      "buildingName": "Syracuse Academy of Science HS",
      "id": 700624143,
      "studentId": 181901330,
      "firstName": "Jasmine",
      "lastName": "Ellerbe",
      "section": 1,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": null,
      "pslLevelName": null,
      "pslColorCode": "#ffffff",
      "REGENTS-CCAI-score": 57,
      "REGENTS-CCAI-colorCode": "#ff6384",
      "REGENTS-CCAI-levelName": "L1",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 43,
      "REGENTS-CCG-colorCode": "#ff6384",
      "REGENTS-CCG-levelName": "L1",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "11",
      "schoolId": 13,
      "buildingId": 9,
      "courseId": 16016,
      "buildingName": "Utica Academy of Science HS",
      "id": 700624178,
      "studentId": 181901372,
      "firstName": "Brandon",
      "lastName": "Wimpenney",
      "section": 1,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": null,
      "pslLevelName": null,
      "pslColorCode": "#ffffff",
      "REGENTS-CCAI-score": 80,
      "REGENTS-CCAI-colorCode": "#36a2eb",
      "REGENTS-CCAI-levelName": "L3",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 73,
      "REGENTS-CCG-colorCode": "#ffcd56",
      "REGENTS-CCG-levelName": "L2",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "11",
      "schoolId": 13,
      "buildingId": 9,
      "courseId": 16016,
      "buildingName": "Utica Academy of Science HS",
      "id": 700624262,
      "studentId": 181901459,
      "firstName": "Tyler",
      "lastName": "Delgado",
      "section": 1,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": null,
      "pslLevelName": null,
      "pslColorCode": "#ffffff",
      "REGENTS-CCAI-score": 86,
      "REGENTS-CCAI-colorCode": "#4bc0c0",
      "REGENTS-CCAI-levelName": "L4",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I",
      "REGENTS-CCG-score": 75,
      "REGENTS-CCG-colorCode": "#ffcd56",
      "REGENTS-CCG-levelName": "L2",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "11",
      "schoolId": 2,
      "buildingId": 6,
      "courseId": 16016,
      "buildingName": "Syracuse Academy of Science HS",
      "id": 700624304,
      "studentId": 181901510,
      "firstName": "Azaryia",
      "lastName": "Howard",
      "section": 1,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": null,
      "pslLevelName": null,
      "pslColorCode": "#ffffff",
      "REGENTS-CCG-score": 58,
      "REGENTS-CCG-colorCode": "#ff6384",
      "REGENTS-CCG-levelName": "L1",
      "REGENTS-CCG-regentsName": "Regents Common Core Geometry"
    },
    {
      "grade": "10",
      "schoolId": 13,
      "buildingId": 9,
      "courseId": 16016,
      "buildingName": "Utica Academy of Science HS",
      "id": 700624359,
      "studentId": 181901580,
      "firstName": "Najalique",
      "lastName": "Taylor",
      "section": 2,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": null,
      "pslLevelName": null,
      "pslColorCode": "#ffffff",
      "REGENTS-CCAI-score": 77,
      "REGENTS-CCAI-colorCode": "#ffcd56",
      "REGENTS-CCAI-levelName": "L2",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I"
    },
    {
      "grade": "10",
      "schoolId": 13,
      "buildingId": 9,
      "courseId": 16016,
      "buildingName": "Utica Academy of Science HS",
      "id": 700624360,
      "studentId": 181901581,
      "firstName": "Tyrique",
      "lastName": "Taylor",
      "section": 2,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": null,
      "pslLevelName": null,
      "pslColorCode": "#ffffff",
      "REGENTS-CCAI-score": 68,
      "REGENTS-CCAI-colorCode": "#ffcd56",
      "REGENTS-CCAI-levelName": "L2",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I"
    },
    {
      "grade": "11",
      "schoolId": 2,
      "buildingId": 6,
      "courseId": 16016,
      "buildingName": "Syracuse Academy of Science HS",
      "id": 700624766,
      "studentId": 192001478,
      "firstName": "Savanna",
      "lastName": "McMullen",
      "section": 3,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": null,
      "pslLevelName": null,
      "pslColorCode": "#ffffff"
    },
    {
      "grade": "11",
      "schoolId": 2,
      "buildingId": 6,
      "courseId": 16016,
      "buildingName": "Syracuse Academy of Science HS",
      "id": 700844527,
      "studentId": 192001562,
      "firstName": "ZamZam",
      "lastName": "Aden",
      "section": 1,
      "courseStateCode": "02056CC",
      "star": null,
      "state": null,
      "regents": null,
      "psaScore": null,
      "psaLevelName": null,
      "psaColorCode": null,
      "peaScore": null,
      "peaLevelName": null,
      "peaColorCode": null,
      "pslScore": null,
      "pslLevelName": null,
      "pslColorCode": "#ffffff",
      "REGENTS-CCAI-score": 71,
      "REGENTS-CCAI-colorCode": "#ffcd56",
      "REGENTS-CCAI-levelName": "L2",
      "REGENTS-CCAI-regentsName": "Regents Common Core Algebra I"
    }
  ]