export const mockData = [
  {
    poolId: 86,
    poolName: "Test Pool",
    poolDescription: "test pool 1",
    poolAbbreviation: "TP1",
    createdAt: "2023-07-25T17:54:25.000Z",
    lastModifiedAt: "2023-07-25T17:54:25.000Z",
    isActive: 1,
    schoolYearId: 2022,
    schoolYear: "2022-2023",
    ownerId: 10009550,
    ownerFirstName: "Abdullah",
    ownerLastName: "Enes",
    stateCourseId: 3,
    stateCourseCode: "01003CC",
    stateCourseName: "ELA III (Common Core) (11th grade)",
    stateCourseSubjectAreaId: 1,
    stateCourseSubjectArea: "English Language and Literature",
    userAccesses: [
      {
        poolAccessId: 55,
        userId: 10009550,
        userFirstName: "Abdullah",
        userLastName: "Enes",
        accessTypeId: 2,
        accessType: "Edit",
      },
      {
        poolAccessId: 55,
        userId: 10009561,
        userFirstName: "Yu-Jui",
        userLastName: "Chang",
        accessTypeId: 2,
        accessType: "Edit",
      },
      {
        poolAccessId: 58,
        userId: 10017890,
        userFirstName: "Irmgard",
        userLastName: "Walker",
        accessTypeId: 2,
        accessType: "Edit",
      },
      {
        poolAccessId: 59,
        userId: 10020892,
        userFirstName: "Teacher",
        userLastName: "Test",
        accessTypeId: 1,
        accessType: "View",
      },
    ],
    dateCreatedForTable: "09-20-2023",
    owner: "Yu-Jui Chang",
    activeForFilter: "Yes",
    canEdit: true,
  },
  {
    poolId: 87,
    poolName: "Test Pool 2",
    poolDescription: "test pool 2",
    poolAbbreviation: "TP2",
    createdAt: "2023-07-25T18:45:48.000Z",
    lastModifiedAt: "2023-07-25T18:45:48.000Z",
    isActive: 1,
    schoolYearId: 2022,
    schoolYear: "2022-2023",
    ownerId: 10009561,
    ownerFirstName: "Yu-Jui",
    ownerLastName: "Chang",
    stateCourseId: 3,
    stateCourseCode: "01003CC",
    stateCourseName: "ELA III (Common Core) (11th grade)",
    stateCourseSubjectAreaId: 1,
    stateCourseSubjectArea: "English Language and Literature",
    userAccesses: [
      {
        poolAccessId: 55,
        userId: 10009561,
        userFirstName: "Yu-Jui",
        userLastName: "Chang",
        accessTypeId: 2,
        accessType: "Edit",
      },
      {
        poolAccessId: 58,
        userId: 10017890,
        userFirstName: "Irmgard",
        userLastName: "Walker",
        accessTypeId: 2,
        accessType: "Edit",
      },
      {
        poolAccessId: 59,
        userId: 10020892,
        userFirstName: "Teacher",
        userLastName: "Test",
        accessTypeId: 1,
        accessType: "View",
      },
    ],
    dateCreatedForTable: "09-20-2023",
    owner: "Yu-Jui Chang",
    activeForFilter: "Yes",
    canEdit: true,
  },
  {
    poolId: 88,
    poolName: "Test Pool 3",
    poolDescription: "test pool 3",
    poolAbbreviation: "CTP",
    createdAt: "2023-07-25T19:23:40.000Z",
    lastModifiedAt: "2023-07-25T19:23:40.000Z",
    isActive: 0,
    schoolYearId: 2022,
    schoolYear: "2022-2023",
    ownerId: 10009561,
    ownerFirstName: "Yu-Jui",
    ownerLastName: "Chang",
    stateCourseId: 3,
    stateCourseCode: "01003CC",
    stateCourseName: "ELA III (Common Core) (11th grade)",
    stateCourseSubjectAreaId: 1,
    stateCourseSubjectArea: "English Language and Literature",
    userAccesses: [
      {
        poolAccessId: 57,
        userId: 10009561,
        userFirstName: "Yu-Jui",
        userLastName: "Chang",
        accessTypeId: 2,
        accessType: "Edit",
      },
    ],
    dateCreatedForTable: "09-20-2023",
    owner: "Yu-Jui Chang",
    activeForFilter: "Yes",
    canEdit: true,
  },
];
